apiVersion: v1
kind: Pod
metadata:
  name: client2-node2-affinity
spec:
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: node 
            operator: In 
            values:
            - node2
  containers:
  - name: client2-node2-affinity
    image: docker.io/ocpqe/hello-pod
