node('maven') {
  // define commands
  def mvnCmd = "mvn"
  // injection of environment variables is not done so set them here...
  def sourceRef = "master"
  def sourceUrl = "https://github.com/ozdael17/
openshift-tasks"
  def devProject = "pipeline-dev"
  def testProject = "pipeline-test"
  def prodProject = "pipeline-prod"
  def applicationName = "jkf-tasks"

  stage 'Build'
    git branch: sourceRef, url: sourceUrl
    sh "${mvnCmd} clean install -DskipTests=true"
  stage 'Test'
    sh "${mvnCmd} test"
  stage 'Deploy in DEV'
    sh "rm -rf oc-build && mkdir -p oc-build/deployments"
    sh "cp target/openshift-tasks.war oc-build/deployments/ROOT.war"
    // clean up. keep the image stream
    sh "oc project ${devProject}"
    sh "oc delete bc,dc,svc,route -l application=${applicationName} -n ${devProject}"
    // create build. override the exit code since it complains about existing imagestream
    sh "oc new-build --name=${applicationName} --image-stream=bin-tasks --binary=true --labels=application=${applicationName} -n ${devProject} || true"
    // build image
    sh "oc start-build ${applicationName} --from-dir=oc-build --wait=true -n ${devProject}"
    // deploy image
    sh "oc new-app ${applicationName}:latest -n ${devProject}"
    sh "oc expose svc/${applicationName} -n ${devProject}"
  stage 'Deploy in TEST'
    // deploy image
    sh "oc new-app ${applicationName}:latest -n ${testProject}"
    sh "oc expose svc/${applicationName} -n ${testProject}"
  stage 'Deploy in PROD'
    // deploy image
    sh "oc new-app ${applicationName}:latest -n ${prodProject}"
    sh "oc expose svc/${applicationName} -n ${prodProject}"
}
