apiVersion: v1
kind: Pod
metadata:
  name: client3-node3-affinity
spec:
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: node 
            operator: In 
            values:
            - node3 
  containers:
  - name: client3-node3-affinity
    image: docker.io/ocpqe/hello-pod
